name: CI
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push-nestjs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Backend Docker image
      uses: docker/build-push-action@v5.1.0
      with:
        context: ./nest-b
        push: true
        tags: shirsho/nest-b:latest
  build-and-push-nextjs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Frontend Docker image
      uses: docker/build-push-action@v5.1.0
      with:
        context: ./next-f
        push: true
        tags: shirsho/next-f:latest
